<?xml version="1.0"?>
<package format="3">
<name>simple_car_description</name>
<version>0.1.0</version>
<description>Minimal URDF car description and launch files to visualize in RViz (ROS 2). This variant uses a plain URDF (no xacro).</description>
<maintainer email="you@example.com">Your Name</maintainer>
<license>Apache-2.0</license>


<buildtool_depend>ament_cmake</buildtool_depend>
<depend>rclcpp</depend>
<depend>std_msgs</depend>
<depend>hardware_interface</depend>
<depend>pluginlib</depend>


<!-- runtime / exec deps -->
<exec_depend>robot_state_publisher</exec_depend>
<exec_depend>joint_state_publisher_gui</exec_depend>
<exec_depend>rviz2</exec_depend>


<export>
<build_type>ament_cmake</build_type>
</export>
</package>