<?xml version="1.0"?>
<package format="3">
  <name>state_feedback_controller</name>
  <version>1.2.16</version>
  <description>State feedback controller for the gz_ros2_controls_demos example of a cart on a 1D track</description>

  <maintainer email="gustavo.comerlato@ufrgs.br">Gustavo Comerlato Rodrigues</maintainer>
  <author>Gustavo Comerlato Rodrigues</author>
  <license>MIT</license>

  <url type="repository">https://github.com/ros-controls/gz_ros2_control</url>

  <depend>controller_interface</depend>
  <depend>hardware_interface</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>pluginlib</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>control_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>gz_ros2_control_demos</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>

  <!-- ros2_control -->
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>effort_controllers</exec_depend>
  <exec_depend>force_torque_sensor_broadcaster</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>